[package]
name = "sentencepiece"
version = "0.1.1"
authors = ["DaniÃ«l de Kok <me@danieldk.eu>"]
edition = "2018"
description = "Binding for the sentencepiece tokenizer"
repository = "https://github.com/danieldk/sentencepiece.git"
documentation = "https://rustdoc.danieldk.eu/sentencepiece"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
num-derive = "0.3"
num-traits = "0.2"
# Generated files are compatible only with the same version
# of protobuf runtime.
protobuf = "= 2.10.1"
sentencepiece-sys = { path = "sentencepiece-sys", version = "0.1.0" }

[build-dependencies]
protoc-rust = { version = "2", optional = true }

[features]
albert-tests = []
proto-compile = [ "protoc-rust" ]
