[package]
name = "sentencepiece"
version = "0.1.0"
authors = ["DaniÃ«l de Kok <me@danieldk.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
