[package]
name = "sentencepiece"
version = "0.1.0"
authors = ["DaniÃ«l de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
libc = "0.2"
num-derive = "0.3"
num-traits = "0.2"
protobuf = "2"
sentencepiece-sys = { path = "sentencepiece-sys" }

[build-dependencies]
protoc-rust = { version = "2" }